#!/usr/bin/env bash
APPDIR='/usr/lib/baby'

export PATH="${APPDIR}/bin:${APPDIR}/usr/local/bin:${PATH}"
export LD_LIBRARY_PATH="${APPDIR}/lib:${APPDIR}/usr/local/lib:${LD_LIBRARY_PATH}"

export PYTHONPATH="/usr/lib/baby/"

"${APPDIR}/usr/local/bin/python3" /usr/lib/baby/.
