#!/usr/bin/env bash
APPDIR='/usr/bin/baby'

export PATH="${APPDIR}/bin:${APPDIR}/usr/local/bin:${PATH}"
export LD_LIBRARY_PATH="${APPDIR}/lib:${APPDIR}/usr/local/lib:${LD_LIBRARY_PATH}"

export PYTHONPATH="/usr/lib/baby/"

"${APPDIR}/venv/bin/python" -m /usr/lib/baby/.
